services:
  config-service:
    image: 127.0.0.1:5000/config-service:latest
    build: ./service-config
    container_name: config-service
    ports:
      - "8088:8088"
    volumes:
      - ./config:/config  # Mounting the local config directory to the container
    environment:
      - SPRING_PROFILES_ACTIVE=native
  eureka-server:
    image: 127.0.0.1:5000/eureka-server:latest
    build: ./service-registry
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - SERVER_PORT=8761
      - HOSTNAME=eureka-server  # Set the HOSTNAME environment variable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  service-department:
    image: 127.0.0.1:5000/service-department:latest
    build: ./service-department
    container_name: service-department
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    command: ["./wait-for-eureka.sh", "eureka-server:8761", "--", "start-service-department"]
    restart: on-failure